### ISSUE TITLE
crash when attempting to scrape a URL

### ISSUE THREAD

**Issue by jjasghar** [dosman711/lita-web-title#8]
```
2015-04-14T19:24:30.149257+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/cinch-2.2.5/lib/cinch/handler.rb:99:in `call'
2015-04-14T19:24:30.149258+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/cinch-2.2.5/lib/cinch/handler.rb:99:in `block in call'
2015-04-14T19:24:30.149260+00:00 app[web.1]:
2015-04-14T19:25:36.856852+00:00 app[web.1]: [2015-04-14 19:25:36 UTC] ERROR: Lita::Handlers::WebTitle crashed. The exception was:
2015-04-14T19:25:36.856858+00:00 app[web.1]: undefined method `strip!' for nil:NilClass
2015-04-14T19:25:36.856860+00:00 app[web.1]: Full backtrace:
2015-04-14T19:25:36.856862+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/lita-web-title-1.0.3/lib/lita/handlers/web_title.rb:13:in `parse_uri_request'
2015-04-14T19:25:36.856864+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/lita-4.3.2/lib/lita/callback.rb:31:in `public_send'
2015-04-14T19:25:36.856871+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/lita-4.3.2/lib/lita/handler/chat_router.rb:70:in `map'
2015-04-14T19:25:36.856866+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/lita-4.3.2/lib/lita/callback.rb:31:in `call'
2015-04-14T19:25:36.856868+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/lita-4.3.2/lib/lita/handler/chat_router.rb:88:in `dispatch_to_route'
2015-04-14T19:25:36.856874+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/lita-4.3.2/lib/lita/robot.rb:58:in `block in receive'
2015-04-14T19:25:36.856869+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/lita-4.3.2/lib/lita/handler/chat_router.rb:73:in `block in dispatch'
2015-04-14T19:25:36.856873+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/lita-4.3.2/lib/lita/handler/chat_router.rb:70:in `dispatch'
2015-04-14T19:25:36.856877+00:00 app[web.1]: /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/set.rb:232:in `each'
2015-04-14T19:25:36.856876+00:00 app[web.1]: /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/set.rb:232:in `each_key'
2015-04-14T19:25:36.856879+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/lita-4.3.2/lib/lita/robot.rb:55:in `map'
2015-04-14T19:25:36.856881+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/lita-4.3.2/lib/lita/robot.rb:55:in `receive'
2015-04-14T19:25:36.856882+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/lita-irc-2.0.2/lib/lita/adapters/irc/cinch_plugin.rb:38:in `dispatch'
2015-04-14T19:25:36.856884+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/lita-irc-2.0.2/lib/lita/adapters/irc/cinch_plugin.rb:18:in `execute'
2015-04-14T19:25:36.856887+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/cinch-2.2.5/lib/cinch/plugin.rb:419:in `block (2 levels) in __register_matchers'
2015-04-14T19:25:36.856891+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/cinch-2.2.5/lib/cinch/handler.rb:99:in `block in call'
2015-04-14T19:25:36.856892+00:00 app[web.1]:
2015-04-14T19:25:36.856889+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/cinch-2.2.5/lib/cinch/handler.rb:99:in `call'
2015-04-14T19:25:36.856885+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/cinch-2.2.5/lib/cinch/plugin.rb:419:in `call'
14:25:50 myhubot > (master)
```

:-1:

**Comment by dosman711** [comment]
This is fixed with commit afdf05d
